// vue/src/components/home/Home.vue
<template>
  <section id="home" class="page-section">
            
      <div id="coverArea" class="cover-area">
        <span v-html="coverHtml[0]"></span>
      </div><!--.cover-text-->
      
  </section><!--#home-->
</template>

<script>
import api from '../../api'
export default {
  data () {
    return {
      coverHtml: []
    }
  },
  methods: {
      loadCoverArea() {
        var _this = this;
        const URL = 'pages/7';
        api.get(URL)
        .then(function(response){
          let page = (response.data);
          _this.coverHtml.push(page.content.rendered);
        })
      }
  },
  mounted() {
    this.loadCoverArea();
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
  @import '../../assets/scss/settings/settings';
  @import '../../assets/scss/tools/tools';
  @import './assets/scss/components/_page-home.scss';
  @import './assets/scss/components/_cover-area.scss';
</style>

// v-react/src/components/Home/index.js
import React, {useState, useEffect} from 'react'

import api from '../../api'

/*import '../../assets/scss/settings/settings'
import '../../assets/scss/tools/tools'
import './assets/scss/components/_page-home.scss'
import './assets/scss/components/_cover-area.scss'*/

export default function Home() {
  
  const [coverHtml,setCoverArea] = useState([]);

  useEffect(() => {
    loadCover()
  })
  function loadCover() {
    const URL = 'pages/7';
    api.get(URL)
    .then(function(response){
      let page = (response.data);
      setCoverArea(page.content.rendered);
    })
  }
  return (
    <div id="home" className="page-section">
            
        <div id="coverArea" className="cover-area">
          <span dangerouslySetInnerHTML={{__html:coverHtml}}></span>
        </div>
        
    </div>
  )
}
