// vue/src/components/funfacts/Funfacts.vue
<template>
  <label  id="funFactsCard" class="fun-facts-card animated" for="checkFunFacts" title="Click to close">
        
      <div class="content">

          <img src="./assets/img/Cube-1s-39px.svg" alt="">

          <h6 class="title">
              some fun fact about me #<span id="funFactID"></span>
          </h6>
          
          <p id="funFacts"></p> 

      </div><!--.content-->

  </label><!--.fun-facts-content-->  
</template>

<script>
//import api from '../../api'
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
  @import '../../assets/scss/settings/settings';
  @import '../../assets/scss/tools/tools';

  @import './assets/scss/components/_fun-facts-card.scss';
  @import './assets/scss/components/_fun-facts-icon.scss';
</style>

// react/src/components/funfacts/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import axios from 'axios';

import './scss/main.scss';
import loading from './img/loading.svg';

const randomFunFacts = () => {
    axios.get('./json/funfacts.json')
    .then(function(response){
        var obj = (response.data);
        var id = Math.floor((Math.random() * obj.length) + 1);
        var factsHTML = obj[id].fact;
        document.getElementById('funFacts').innerHTML = factsHTML;
        document.getElementById('funFactID').innerHTML = id;
    })
}

class FunFacts extends React.Component {
    componentDidMount() {
        randomFunFacts();  
    } 
    render() {
        return (
            <label id="funFactsCard" className="fun-facts-card animated" htmlFor="checkFunFacts" title="Click to close">
        
                <div className="content">

                    <img src={loading} alt=""/>

                    <h6 className="title">
                        some fun fact about me #<span id="funFactID"></span>
                    </h6>
                    
                    <p id="funFacts"></p>

                </div>

            </label>
        );
    }
}  

//exportando o componente
export default FunFacts;
