// vue/src/components/home/Home.vue
<template>
  <section id="home" class="page-section">
            
      <div id="coverArea" class="cover-area"></div><!--.cover-text-->
      
  </section><!--#home-->
</template>

<script>
import axios from 'axios'
export default {
  methods: {
      loadCoverArea: function() {
        axios.get('http://localhost/jadson.dev/portfolio/wordpress/wp-json/wp/v2/pages/7')
        .then(function(response){
          let page = (response.data);
          let cover = document.getElementById('coverArea');
          cover.innerHTML = page.content.rendered;
        })
      }
  },
  mounted() {
    this.loadCoverArea();
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
  @import '../../assets/scss/settings/settings';
  @import '../../assets/scss/tools/tools';
  @import './assets/scss/components/_page-home.scss';
  @import './assets/scss/components/_cover-area.scss';
</style>

// react/src/components/home/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import axios from 'axios';

import './scss/main.scss';
import bG from './img/bg-home.jpg';

const loadCoverArea = () => {
    axios.get('./json/cover.json')
    .then(function(response){
        let obj = (response.data);
        let cover = document.getElementById('coverArea');

        let greeting = document.createElement('SPAN');
        greeting.innerHTML = obj[0].greeting;
        cover.appendChild(greeting);
        
        let me = document.createElement('H2');
        me.innerHTML = obj[0].me;
        cover.appendChild(me);

        let profissional = document.createElement('H1');
        profissional.innerHTML = obj[0].profissional;
        cover.appendChild(profissional);

        let slug = document.createElement('SMALL');
        slug.innerHTML = obj[0].slug;
        cover.appendChild(slug);
    })
}

class Home extends React.Component {
    componentDidMount () {
        loadCoverArea();
    }
    render() {
        return (
            <section id="home" className="page-section">
                <div id="coverArea" className="cover-area"></div>
            </section>
        )
    }
}

export default Home;
