// vue/src/components/timeline/Timeline.vue
<template>
  <div class="content-side timeline">
     
      <dl id="timeLine" class="timeline-information">
        <dt class="year">
          <span v-html="this.year"></span>
        </dt>
        <dd class="item" v-for="events in event" v-bind:key="events" v-html="events"></dd>
      </dl>
      
      <div id="timeLinePagination" class="timeline-pagination"> 
        <label class="item" v-for="(item,index) in objEvents" v-bind:key="item">
          <input type="radio" v-if="(index === 0)" checked name="timeline" :value="index" autocomplete="off" v-on:change="changeTimeLine(index)">
          <input type="radio" v-else=""  name="timeline" :value="index" autocomplete="off" v-on:change="changeTimeLine(index)">
          <i class="bullet"></i>
          <span class="year" :data-year-yyyy="item.year" :data-year-yy="String(item.year).substring(2,4)"></span>
        </label>
      </div>

  </div><!--.timeline-->
</template>

<script>
import api from '../../api'
export default {
  data() {
    return {
         objEvents: [],
         event: [],
         year: Number
    }
  },
  methods: {
      loadTimeLine: function() {
        var _this = this; 
        const URL = 'timeline?per_page=99&filter[orderby]=date&order=desc';
        api.get(URL)
        .then(function(response){
          var obj = (response.data)
          //primeiro valor do objeto para o ano atual
          var currentYear = obj[0].date.split('-')
          currentYear = parseInt(currentYear[0])
          //inicia o objeto de eventos e o array de evento
          var events = {}
          var event = []
          for (var i in obj) {
            //pega o ano
            var year = obj[i].date.split('-');
            year = parseInt(year[0])
            //se o ano atual for igual ao ano do item
            if (year === currentYear) {
              //adiciona o item ao array de evento
              event.push(obj[i].title.rendered)
            }  
            if (year !== currentYear) {
              //atualiza o objeto de eventos
              events.year = currentYear
              events.events = event
              //adiciona o objeto de evento ao array principal
              _this.objEvents.push(events)
              //limpa os objetos e array
              events = {}
              event = []
              //starta os valores 
              events.year = year
              events.events = event.push(obj[i].title.rendered)
            }  
            //atribui o novo valor para o ano atual
            currentYear = year       
          }
          _this.event = _this.objEvents[0].events
          _this.year  = _this.objEvents[0].year
        })         
      },
      changeTimeLine: function(indexYear) {
         this.event = this.objEvents[indexYear].events
         this.year = this.objEvents[indexYear].year
      }
  },
  mounted() {
    this.loadTimeLine()
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
  @import '../../assets/scss/settings/settings';
  @import '../../assets/scss/tools/tools';
  @import './assets/scss/objects/_content-side.scss';
  @import './assets/scss/components/_timeline.scss';
</style>

// v-react/src/components/Timeline/index.js
import React, { useState, useEffect } from 'react'

import api from '../../api'

import './assets/scss/objects/_content-side.scss';
import './assets/scss/components/_timeline.scss';

export default function Timeline() {

  let [objEvents,setObjEvents] = useState([])
  let [eventos,setEvent] = useState([])
  let [year,setYear] = useState(Number)

  useEffect(() => {
    loadTimeLine()    
  },[])

  useEffect(()=> {
    if (objEvents.length > 0) {
      setEvent(objEvents[0].eventos)
      setYear(objEvents[0].year)
    }
  },[objEvents])

  function loadTimeLine() {
    const URL = 'timeline?per_page=99&filter[orderby]=date&order=desc';
    api.get(URL)
    .then(function(response){
      var obj = (response.data)
      //primeiro valor do objeto para o ano atual
      var currentYear = obj[0].date.split('-')
      currentYear = parseInt(currentYear[0])
      //inicia o objeto de eventos e o array de evento
      var events = {}
      var event = []
      for (var i in obj) {
        //pega o ano
        var year = obj[i].date.split('-');
        year = parseInt(year[0])
        //se o ano atual for igual ao ano do item
        if (year === currentYear) {
          //adiciona o item ao array de evento
          event.push(obj[i].title.rendered)
        }  
        if (year !== currentYear) {
          //atualiza o objeto de eventos
          events.year = currentYear
          events.eventos = event
          events.id = i
          //adiciona o objeto de evento ao array principal
          setObjEvents(objEvents => [...objEvents,events])
          //limpa os objetos e array
          events = {}
          event = []
          //starta os valores 
          events.year = year
          events.eventos = event.push(obj[i].title.rendered)
        }  
        //atribui o novo valor para o ano atual
        currentYear = year       
      }
    })      
  }
  function changeTimeLine(indexYear) {
     setEvent(objEvents[indexYear].eventos)
     setYear(objEvents[indexYear].year)
  }

  return (
    
    <div className="content-side timeline">
     
      <dl id="timeLine" className="timeline-information">
        <dt className="year">
          <span dangerouslySetInnerHTML={{__html:year}}></span>
        </dt>
        {eventos.map((item) => (
          <dd className="item" dangerouslySetInnerHTML={{__html:eventos}}></dd>
        ))}
      </dl>

      <div id="timeLinePagination" className="timeline-pagination">
          {objEvents.map((item,index) =>
          {
            var checkItem = (index === 0) ? true : false
            return (
              <label key={item.id} className="item">
                <input type="radio" name="timeline" defaultChecked={checkItem} value={index} autoComplete="off" onChange={() => changeTimeLine(index)}/>
                <i className="bullet"></i>
                <span>{item.year}</span>
              </label>
            )
          })}
      </div>

    </div>
  )
}
