// v-react/src/components/Side/index.js
import React from 'react'

import Menu from './../Menu'
import profilePic from './assets/img/jadson_moreira.webp'

import './assets/scss/objects/_side.scss';
import './assets/scss/components/_side.scss';
import './assets/scss/components/_profile-pic.scss';
import './assets/scss/components/_credits.scss';

export default function Side() {

  return (
    <aside className="side">
      <figure className="profile-pic">
          <span className="pic-rounded">
              <img src={profilePic} className="img" alt="foto perfil"/>                
          </span>
      </figure>
      <Menu/>
      <span className="credits">
          Done with <i className="material-icons heart">favorite</i> and <i className="material-icons song">audiotrack</i>
      </span>
    </aside> 
  )
}

// vue/src/components/side/Side.vue
<template>
  <aside class="side">
      <figure class="profile-pic">
          <span class="pic-rounded">
              <img src="./assets/img/jadson_moreira.webp" class="img" alt="foto perfil">                
          </span>
      </figure>
      <Menu/>
      <span class="credits">
          Done with <i class="material-icons heart">favorite</i> and <i class="material-icons song">audiotrack</i>
      </span>
  </aside>  
</template>

<script>
  import Menu from '../menu/Menu'
  export default {
  name: 'Side',
  components: {
    Menu
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
  @import '../../assets/scss/settings/settings';
  @import '../../assets/scss/tools/tools';

  @import './assets/scss/objects/_side.scss';
  @import './assets/scss/components/_side.scss';
  @import './assets/scss/components/_profile-pic.scss';
  @import './assets/scss/components/_credits.scss';
</style>
