// vue/src/components/timeline/Timeline.vue
<template>
  <div class="content-side timeline">
      
      <dl id="timeLine" class="timeline-information">
        <dt class="year">
          <span v-html="objEvents[0].year"></span>
        </dt>
        <dd class="item" v-for="events in objEvents[0].events" v-bind:key="events" v-html="events"></dd>
      </dl><!--.timeline-information-->
      
      <div id="timeLinePagination" class="timeline-pagination">
        <label class="item" v-for="(year,index) in objYears" v-bind:key="year">
          <input type="radio" v-if="index === 0" checked="checked" name="timeline" :value="year" autocomplete="off" v-on:change="changeTimeLine(year)">
          <input type="radio" v-else name="timeline" :value="year" autocomplete="off" v-on:change="changeTimeLine(year)">
          <i class="bullet"></i>
          <span>{{year}}</span>
        </label>
      </div><!--.timeline-pagination-->

  </div><!--.timeline-->
</template>

<script>
import api from '../../api'
export default {
  data() {
    return {
      objYears: [],
      objEvents: []      
    }
  },
  methods: {
      loadTimeLine: function() {
       var _this = this; 
       const URL = 'timeline?per_page=99&filter[orderby]=date&order=desc';
       api.get(URL)
      .then(function(response){
        var obj = (response.data);
        var years = new Array();
        var events = new Array(); 
        for (var i=0;i<obj.length;i++) {
          let year = obj[i].date.split('-');  
          let lastYear = obj[0].date.split('-'); 
          years.push(year[0]);
          if (parseInt(year[0]) === parseInt(lastYear[0])) {
            events.push(obj[i].title.rendered);            
          }
        }
        years = years.filter((v,i,a) => a.indexOf(v) === i);
        for (i in years) {
          let year = years[i];
          _this.objYears.push(year);
          
        }
        _this.objEvents = [];
        _this.objEvents.push({'year':2012,events});
      });
    },
    changeTimeLine: function(selectYear) {
      var _this = this;
      const URL = 'timeline?per_page=99&filter[orderby]=date&order=desc';
      api.get(URL)
      .then(function(response){
        var obj = (response.data);  
        var events = new Array();     
        for (let i in obj) {
          let year = obj[i].date.split('-');
          if (parseInt(year) === parseInt(selectYear)) {
            events.push(obj[i].title.rendered);            
          }
        }
        _this.objEvents = [];
        _this.objEvents.push({'year':selectYear,events});
      }); 
    }
  },
  mounted() {
    this.loadTimeLine();
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
  @import '../../assets/scss/settings/settings';
  @import '../../assets/scss/tools/tools';
  @import './assets/scss/objects/_content-side.scss';
  @import './assets/scss/components/_timeline.scss';
</style>

// vite/src/components/Timeline/index.tsx
import React, { useState, useEffect } from 'react'

import api from '../../api'
import type { TimelineEvent } from '../../types/api'

import './assets/scss/objects/_content-side.scss';
import './assets/scss/components/_timeline.scss';

type TimelineYear = {
  id: string;
  year: number;
  eventos: string[];
};

export default function Timeline() {

  const [objEvents,setObjEvents] = useState<TimelineYear[]>([])
  const [eventos,setEvent] = useState<string[]>([])
  const [year,setYear] = useState<number | null>(null)

  useEffect(() => {
    loadTimeLine()    
  },[])

  useEffect(()=> {
    if (objEvents.length > 0) {
      setEvent(objEvents[0].eventos)
      setYear(objEvents[0].year)
    }
  },[objEvents])

  function loadTimeLine() {
    const URL = 'timeline';
    api.get<TimelineEvent[]>(URL)
    .then(function(response){
      const obj = (response.data)

      const eventsByYear = obj.reduce<TimelineYear[]>((timeline, item) => {
        const itemYear = Number.parseInt(item.date.split('-')[0], 10)
        const currentYear = timeline[timeline.length - 1]

        if (currentYear?.year === itemYear) {
          currentYear.eventos.push(item.title)
          return timeline
        }

        timeline.push({
          id: String(timeline.length),
          year: itemYear,
          eventos: [item.title],
        })

        return timeline
      }, [])

      setObjEvents(eventsByYear)
    })      
  }
  function changeTimeLine(indexYear: number) {
    const selectedYear = objEvents[indexYear]

    if (selectedYear) {
      setEvent(selectedYear.eventos)
      setYear(selectedYear.year)
      }
  }

  return (
    
    <div className="content-side timeline">
     
      <dl id="timeLine" className="timeline-information">
        <dt className="year">
          <span>{year}</span>
        </dt>
        {eventos.map((item,index) => (
          <dd className="item" key={index}  dangerouslySetInnerHTML={{__html:item}}></dd>
        ))}
      </dl>

      <div id="timeLinePagination" className="timeline-pagination">
          {objEvents.map((item,index) =>
          {
            const checkItem = (index === 0) ? true : false
            return (
              <label key={item.id} className="item">
                <input type="radio" name="timeline" defaultChecked={checkItem} value={index} autoComplete="off" onChange={() => changeTimeLine(index)}/>
                <i className="bullet"></i>
                <span>{item.year}</span>
              </label>
            )
          })}
      </div>

    </div>
  )
}
