// v-react/src/components/Contact/index.js
import React, {useState,useEffect} from 'react'

import api from '../../api'

import './assets/scss/components/_contact-pointers.scss'
import './assets/scss/components/_container-contact.scss'

export default function Contact() {
  let [social,setSocial] = useState([])
  useEffect(() => {
    loadContacts()
  },[])
  function loadContacts() {
    //document.getElementById('checkFunFacts').click()
    const URL = 'social?per_page=99&filter[orderby]=date&order=asc';
    api.get(URL)
    .then(function(response){
      var obj = (response.data);
      for (var i = 0; i < obj.length; i++) {

        let label = obj[i].title.rendered
        let link = obj[i].excerpt.rendered
        link = link.replace('<p>','')
        link = link.replace('</p>','')
        let title = obj[i].content.rendered
        title = title.replace('<p>','')
        title = title.replace('</p>','')
        
        setSocial(social => [...social,{'label': label, 'link':link, 'title':title}])
      }
    })
    .finally(function(){
      //document.getElementById('checkFunFacts').checked = false
    })
  }
  return (
    <section id="contact" className="page-section">
      
      <h1 className="title">
          Contact me
      </h1>

      <div className="content">

          <div data-simplebar-auto-hide="false" className="main-content container-contact">
              
              <div id="contactBox" className="container-form">
                {social.map((item,index) => {
                  return (                
                    <dl className="contact-pointers" key={'contact'+index}>
                      {index === 0 ? 
                        <dt className="title" dangerouslySetInnerHTML={{__html:item.label}}></dt>
                      : null }
                      {index === 1 ?
                        <dd className="item" dangerouslySetInnerHTML={{__html:item.title}}></dd>
                      : null }
                      {index > 1 ?
                        <dd className="item">
                          <a href={item.link} target="_blank" rel="noopener noreferrer" title={item.title} className="title">{item.label}</a>
                        </dd>
                      : null }
                    </dl>
                  )
                })}
              </div>

          </div>
  
      </div>

  </section>
  )
}

// vue/src/components/contact/Contact.vue
<template>
  <section id="contact" class="page-section">
      
      <h1 class="title">
          Contact me
      </h1>

      <div class="content">

          <simplebar data-simplebar-auto-hide="false" class="main-content container-contact">
              
              <div id="contactBox" class="container-form">
                
                <dl class="contact-pointers" v-for="(item,index) in social" v-bind:key="item">
                  <dt class="title" v-if="index === 0" v-html="item.label"></dt>
                  <dd class="item"  v-if="index === 1" v-html="item.title"></dd>
                  <dd class="item" v-if="index > 1">
                    <a :href="item.link" target="_blank" :title="item.title" class="title">{{item.label}}</a>
                  </dd>
                </dl>

              </div><!--.container-form-->

          </simplebar><!--.contact-form-->
  
      </div><!--.content-->

  </section><!--#contact-->  
</template>

<script>
  import api from '../../api'
  import simplebar from 'simplebar-vue';

  export default {
    components: {
      simplebar
    },
    data () {
      return {
        social: []
      }
    },
    methods: {
      loadContacts: function() {
        document.getElementById('checkFunFacts').click()
        var _this = this;
        const URL = 'social?per_page=99&filter[orderby]=date&order=asc';
        api.get(URL)
        .then(function(response){
          var obj = (response.data);
          for (var i = 0; i < obj.length; i++) {

            let label = obj[i].title.rendered;
            let link = obj[i].excerpt.rendered;
            link = link.replace('<p>','');
            link = link.replace('</p>','');
            let title = obj[i].content.rendered;
            title = title.replace('<p>','');
            title = title.replace('</p>','');
            
            _this.social.push({'label': label, 'link':link, 'title':title});
          }
        })
        .finally(function(){
          document.getElementById('checkFunFacts').checked = false
        })
      }
    },
    mounted() {
      this.loadContacts();
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
  @import '../../assets/scss/settings/settings';
  @import '../../assets/scss/tools/tools';

  @import './assets/scss/components/_contact-pointers.scss';
  @import './assets/scss/components/_container-contact.scss';
</style>
