// v-react/src/components/Post/index.js
import React, {useState,useEffect} from 'react'

import {useParams} from 'react-router-dom'

import api from '../../api'

import './assets/scss/components/_post.scss'

export default function Post() {

    let [title,setTitle] = useState(String)
    let [date,setDate] = useState(String)
    let [content,setContent] = useState(String)
    const { slug } = useParams()

    useEffect(() => {
        //document.getElementById('checkFunFacts').click()
        let URL = 'posts?slug='+slug
        api.get(URL)
        .then(function(response){
            let obj = response.data
            setTitle(obj[0].title.rendered)
            setContent(obj[0].content.rendered)
            let date = new Date(obj[0].date_gmt)
            date = date.toUTCString()
            date = date.split(' GMT')[0]
            setDate(date.substring(0, date.length - 9))
        })
        .finally(function(){
            //document.getElementById('checkFunFacts').checked = false
        })
    },[slug])

    return (
        <section id="post" className="page-section">
            
            <h1 className="title">
                {title}
            </h1>

            <time className="post-date" datetime={date}>
                {date}
            </time>

            <div data-simplebar-auto-hide="false" className="content content-post">

                <div dangerouslySetInnerHTML={{__html:content}}></div>
        
            </div>

        </section>
    )
}

// vue/src/components/blog/Post.vue
<template>
  <section id="blog" class="page-section">
            
      <h1 class="title">
          Recent articles
      </h1>

      <simplebar data-simplebar-auto-hide="false" class="content article-list">

          <div id="listingPosts">
              <div class="article" v-for="item in article" v-bind:key="item">
          
                  <h2 class="title">
                      <a :href="item.link" class="link">{{item.title}}</a>
                  </h2>

                  <time class="date" datetime="">{{item.data}}</time>
                      
              </div>
          </div><!--#listingPost-->
  
      </simplebar><!--.content-->

  </section><!--#blog--> 
</template>

<script>
  import api from '../../api'
  import simplebar from 'simplebar-vue';

  export default {
    name: 'Blog', 
    components: {
      simplebar
    },
    data () {
      return {
        article: []
      }
    },
    methods: {
      loadBlogPosts: function() {
        var _this = this;
        const URL = 'posts/';
        api.get(URL)
        .then(function(response){
          var obj = (response.data);
          for (var i = 0; i < obj.length; i++) {

            let link = obj[i].link;
            let title = obj[i].title.rendered;

            let date = obj[i].date.split('T')[0];
            
            _this.article.push({'title': title, 'link':link, 'data':date});
          }
        })
      }
    },
    mounted() {
      this.loadBlogPosts();
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
  @import '../../assets/scss/settings/settings';
  @import '../../assets/scss/tools/tools';

  @import './assets/scss/components/_article.scss';
</style>
